apiVersion : apps/v1
kind: Deployment
metadata:
  name: "myaks-ec10"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "myaks-ec10"
  template:
    metadata:
      labels:
        app: "myaks-ec10"
    spec:
      containers:
        - name: "myaks-ec10"
          image: "myacs20222.azurecr.io/myaks"
          ports:
          - containerPort: 80