apiVersion : apps/v1
kind: Deployment
metadata:
  name: "myadks-8e63"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "myadks-8e63"
  template:
    metadata:
      labels:
        app: "myadks-8e63"
    spec:
      containers:
        - name: "myadks-8e63"
          image: "myacrs2022.azurecr.io/myadks"
          ports:
          - containerPort: 80