apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aks2023-1102"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aks2023-1102"
  template:
    metadata:
      labels:
        app: "aks2023-1102"
    spec:
      containers:
        - name: "aks2023-1102"
          image: "mywiproacr2023.azurecr.io/aks2023"
          ports:
          - containerPort: 80