apiVersion : apps/v1
kind: Deployment
metadata:
  name: "myakscluster-0c64"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "myakscluster-0c64"
  template:
    metadata:
      labels:
        app: "myakscluster-0c64"
    spec:
      containers:
        - name: "myakscluster-0c64"
          image: "azure2aksacr.azurecr.io/myakscluster"
          ports:
          - containerPort: 80