apiVersion : apps/v1
kind: Deployment
metadata:
  name: "myakscluster-3ac7"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "myakscluster-3ac7"
  template:
    metadata:
      labels:
        app: "myakscluster-3ac7"
    spec:
      containers:
        - name: "myakscluster-3ac7"
          image: "myacs2022.azurecr.io/myakscluster"
          ports:
          - containerPort: 9090