apiVersion : apps/v1
kind: Deployment
metadata:
  name: "myaks-be86"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "myaks-be86"
  template:
    metadata:
      labels:
        app: "myaks-be86"
    spec:
      containers:
        - name: "myaks-be86"
          image: "myacr20221.azurecr.io/myaks"
          ports:
          - containerPort: 80