apiVersion : apps/v1
kind: Deployment
metadata:
  name: "myakscluster-7cc5"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "myakscluster-7cc5"
  template:
    metadata:
      labels:
        app: "myakscluster-7cc5"
    spec:
      containers:
        - name: "myakscluster-7cc5"
          image: "myacr9999.azurecr.io/myakscluster"
          ports:
          - containerPort: 80