apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aks-1398"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aks-1398"
  template:
    metadata:
      labels:
        app: "aks-1398"
    spec:
      containers:
        - name: "aks-1398"
          image: "votingapp2.azurecr.io/aks"
          ports:
          - containerPort: 80