apiVersion: v1
kind: Service
metadata:
    name: "myakscluster-3ac7"
    labels:
        app: "myakscluster-3ac7"
spec:
    type: LoadBalancer
    ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: http
    selector:
        app: "myakscluster-3ac7"