apiVersion: v1
kind: Service
metadata:
    name: "myaks-3c2c"
    labels:
        app: "myaks-3c2c"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "myaks-3c2c"