apiVersion: v1
kind: Service
metadata:
    name: "myadks-8e63"
    labels:
        app: "myadks-8e63"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "myadks-8e63"