on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n votingapp2 -g votingapp2911b-rg --location "East US" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n votingapp2 --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n votingapp2 --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n votingapp2 --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: votingapp2.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/result" -f  "result/Dockerfile" -t votingapp2.azurecr.io/aks:${{ github.sha }} --label dockerfile-path=result/Dockerfile
        docker push votingapp2.azurecr.io/aks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_aks_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aks9751 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aks9751`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aks9751
        container-registry-url: votingapp2.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: aksdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aks9751
        manifests: |
          manifests/deployment-2.yml
          manifests/service-2.yml
        images: |
          votingapp2.azurecr.io/aks:${{ github.sha }}
        imagepullsecrets: |
          aksdockerauth   
