on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: myacs2022.azurecr.io
        username: ${{ secrets.acr_myacs2022_username }}
        password: ${{ secrets.acr_myacs2022_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/result" -f  "result/Dockerfile" -t myacs2022.azurecr.io/myakscluster:${{ github.sha }} --label dockerfile-path=result/Dockerfile
        docker push myacs2022.azurecr.io/myakscluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_myakscluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep myaks-clusterb8d9 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace myaks-clusterb8d9`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: myaks-clusterb8d9
        container-registry-url: myacs2022.azurecr.io
        container-registry-username: ${{ secrets.acr_myacs2022_username }}
        container-registry-password: ${{ secrets.acr_myacs2022_password }}
        secret-name: myaksclusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: myaks-clusterb8d9
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          myacs2022.azurecr.io/myakscluster:${{ github.sha }}
        imagepullsecrets: |
          myaksclusterdockerauth
