on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n mytcapp -g mytcappa794-rg --location "South India" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n mytcapp --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n mytcapp --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n mytcapp --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: mytcapp.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/result" -f  "result/Dockerfile" -t mytcapp.azurecr.io/myaksapps:${{ github.sha }} --label dockerfile-path=result/Dockerfile
        docker push mytcapp.azurecr.io/myaksapps:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_myaksapps_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep myaks-appsa14a | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace myaks-appsa14a`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: myaks-appsa14a
        container-registry-url: mytcapp.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: myaksappsdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: myaks-appsa14a
        manifests: |
          manifests/deployment-6.yml
          manifests/service-6.yml
        images: |
          mytcapp.azurecr.io/myaksapps:${{ github.sha }}
        imagepullsecrets: |
          myaksappsdockerauth   
