on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: myacr20221.azurecr.io
        username: ${{ secrets.acr_myacr20221_username }}
        password: ${{ secrets.acr_myacr20221_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/result" -f  "result/Dockerfile" -t myacr20221.azurecr.io/myaks:${{ github.sha }} --label dockerfile-path=result/Dockerfile
        docker push myacr20221.azurecr.io/myaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_myaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep myaks99fa | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace myaks99fa`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: myaks99fa
        container-registry-url: myacr20221.azurecr.io
        container-registry-username: ${{ secrets.acr_myacr20221_username }}
        container-registry-password: ${{ secrets.acr_myacr20221_password }}
        secret-name: myaksdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: myaks99fa
        manifests: |
          manifests/deployment-5.yml
          manifests/service-5.yml
        images: |
          myacr20221.azurecr.io/myaks:${{ github.sha }}
        imagepullsecrets: |
          myaksdockerauth
